// <auto-generated />
namespace MyWalletz.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class TransactionMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TransactionMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201305181706550_TransactionMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
