// <auto-generated />
namespace MyWalletz.DataAccess.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class RenamedTablesMigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RenamedTablesMigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201306021911390_RenamedTablesMigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
